### ISSUE TITLE
FR: Maintain query strings on exact match patterns

### ISSUE THREAD

**Issue by stuartcusackie** [riasvdv/statamic-redirect#180]
We ran into a bit of trouble today on a project that needs to maintain query strings for marketing campaigns. I [opened an issue](https://github.com/riasvdv/statamic-redirect/issues/179) about it earlier.

I'm wondering if we can maintain query strings by default on exact match rules, or even to have a checkbox to choose. As it stands, this project will have to use regex patterns for all of its redirects and this will lead to confusion in the future.

Thanks!

**Comment by digilist** [comment]
@riasvdv thank you for implementing this feature! I noticed two issues:

1. The config is read via `config('redirect.preserve_query_strings')` and not `config('statamic.redirect.preserve_query_strings')`, so that it needs a separate configuration file.
2. If the redirect destination already defines a query string, it can result in URLs like this `/example?foo=bar?foo=bar`. I think it would be better to merge these.

It would be great if you can look into this :blush:

**Comment by riasvdv** [comment]
1. Oops! That was definitely a typo, fixed in the latest release 👍 
2. Can you make a separate issue for this? Then I'll try to take a look at it soon

**Comment by digilist** [comment]
Thank you for the quick fix! I've opened #192 for the second issue.
